// Mapping FIPS 10-4 (2-letter) to ISO 3166-1 alpha-3 (3-letter)
// GDELT uses FIPS codes for its location metadata.
export const fipsToIso3 = {
    'AF': 'AFG', 'AX': 'ALA', 'AL': 'ALB', 'AG': 'DZA', 'AQ': 'ATA', 'AN': 'AND', 'AO': 'AGO',
    'AV': 'AIA', 'AY': 'ATA', 'AC': 'ATG', 'AR': 'ARG', 'AM': 'ARM', 'AA': 'ABW', 'AU': 'AUS',
    'AS': 'AUS', 'AJ': 'AZE', 'BF': 'BHS', 'BA': 'BHR', 'BG': 'BGD', 'BB': 'BRB', 'BO': 'BLR',
    'BE': 'BEL', 'BH': 'BLZ', 'BN': 'BEN', 'BD': 'BMU', 'BT': 'BTN', 'BL': 'BOL', 'BK': 'BIH',
    'BC': 'BWA', 'BV': 'BVT', 'BR': 'BRA', 'IO': 'IOT', 'VI': 'VGB', 'BX': 'BRN', 'BU': 'BGR',
    'UV': 'BFA', 'BM': 'MMR', 'BY': 'BDI', 'CB': 'KHM', 'CM': 'CMR', 'CA': 'CAN', 'CV': 'CPV',
    'CJ': 'CYM', 'CT': 'CAF', 'CD': 'TCD', 'CI': 'CHL', 'CH': 'CHN', 'KT': 'CXR', 'CK': 'CCK',
    'CO': 'COL', 'CN': 'COM', 'CF': 'COG', 'CG': 'COD', 'CW': 'COK', 'CS': 'CRI', 'IV': 'CIV',
    'HR': 'HRV', 'CU': 'CUB', 'CY': 'CYP', 'EZ': 'CZE', 'DA': 'DNK', 'DJ': 'DJI', 'DO': 'DMA',
    'DR': 'DOM', 'EC': 'ECU', 'EG': 'EGY', 'ES': 'SLV', 'EK': 'GNQ', 'ER': 'ERI', 'EN': 'EST',
    'ET': 'ETH', 'FK': 'FLK', 'FO': 'FRO', 'FJ': 'FJI', 'FI': 'FIN', 'FR': 'FRA', 'FG': 'GUF',
    'FP': 'PYF', 'FS': 'ATF', 'GB': 'GAB', 'GA': 'GMB', 'GG': 'GEO', 'GM': 'DEU', 'GH': 'GHA',
    'GI': 'GIB', 'GR': 'GRC', 'GL': 'GRL', 'GJ': 'GRD', 'GP': 'GLP', 'GQ': 'GUM', 'GT': 'GTM',
    'GK': 'GGY', 'GV': 'GIN', 'PU': 'GNB', 'GY': 'GUY', 'HA': 'HTI', 'HM': 'HMD', 'VT': 'VAT',
    'HO': 'HND', 'HK': 'HKG', 'HU': 'HUN', 'IC': 'ISL', 'IN': 'IND', 'ID': 'IDN', 'IR': 'IRN',
    'IZ': 'IRQ', 'EI': 'IRL', 'IM': 'IMN', 'IS': 'ISR', 'IT': 'ITA', 'JM': 'JAM', 'JN': 'JNM',
    'JA': 'JPN', 'JE': 'JEY', 'JO': 'JOR', 'KZ': 'KAZ', 'KE': 'KEN', 'KR': 'KIR', 'KP': 'PRK',
    'KS': 'KOR', 'KV': 'KOS', 'KU': 'KWT', 'KG': 'KGZ', 'LA': 'LAO', 'LG': 'LVA', 'LE': 'LBN',
    'LT': 'LSO', 'LI': 'LBR', 'LY': 'LBY', 'LS': 'LIE', 'LH': 'LTU', 'LU': 'LUX', 'MC': 'MAC',
    'MK': 'MKD', 'MA': 'MDG', 'MI': 'MWI', 'MY': 'MYS', 'MV': 'MDV', 'ML': 'MLI', 'MT': 'MLT',
    'IM': 'IMN', 'RM': 'MHL', 'MB': 'MTQ', 'MR': 'MRT', 'MP': 'MUS', 'MF': 'MYT', 'MX': 'MEX',
    'FM': 'FSM', 'MD': 'MDA', 'MN': 'MCO', 'MG': 'MNG', 'MJ': 'MNE', 'MH': 'MSR', 'MO': 'MAR',
    'MZ': 'MOZ', 'WA': 'NAM', 'NR': 'NRU', 'NP': 'NPL', 'NL': 'NLD', 'NC': 'NCL', 'NZ': 'NZL',
    'NU': 'NIC', 'NG': 'NER', 'NI': 'NGA', 'NE': 'NIU', 'NF': 'NFK', 'CQ': 'MNP', 'NO': 'NOR',
    'MU': 'OMN', 'PK': 'PAK', 'PS': 'PLW', 'PM': 'PAN', 'PP': 'PNG', 'PA': 'PRY', 'PE': 'PER',
    'RP': 'PHL', 'PC': 'PCN', 'PL': 'POL', 'PO': 'PRT', 'RQ': 'PRI', 'QA': 'QAT', 'RE': 'REU',
    'RO': 'ROU', 'RS': 'RUS', 'RW': 'RWA', 'SH': 'SHN', 'SC': 'KNA', 'ST': 'LCA', 'SB': 'SPM',
    'VC': 'VCT', 'WS': 'WSM', 'SM': 'SMR', 'TP': 'STP', 'SA': 'SAU', 'SG': 'SEN', 'RI': 'SRB',
    'SE': 'SYC', 'SL': 'SLE', 'SN': 'SGP', 'LO': 'SVK', 'SI': 'SVN', 'BP': 'SLB', 'SO': 'SOM',
    'SF': 'ZAF', 'SX': 'SGS', 'SS': 'SSD', 'SP': 'ESP', 'CE': 'LKA', 'SU': 'SDN', 'NS': 'SUR',
    'SV': 'SJM', 'WZ': 'SWZ', 'SW': 'SWE', 'SZ': 'CHE', 'SY': 'SYR', 'TW': 'TWN', 'TI': 'TJK',
    'TZ': 'TZA', 'TH': 'THA', 'TL': 'TLS', 'TO': 'TGO', 'TL': 'TKL', 'TN': 'TON', 'TD': 'TTO',
    'TS': 'TUN', 'TU': 'TUR', 'TX': 'TKM', 'TK': 'TCA', 'TV': 'TUV', 'UG': 'UGA', 'UP': 'UKR',
    'AE': 'ARE', 'UK': 'GBR', 'US': 'USA', 'UY': 'URY', 'UZ': 'UZB', 'NH': 'VUT', 'VE': 'VEN',
    'VM': 'VNM', 'VQ': 'VIR', 'WF': 'WLF', 'WE': 'PSE', 'WI': 'ESH', 'YM': 'YEM', 'ZA': 'ZMB',
    'ZI': 'ZWE'
};

export const fipsToDisplayName = {
    'US': 'USA',
    'UK': 'United Kingdom',
    'CH': 'China',
    'RS': 'Russia',
    'FR': 'France',
    'GM': 'Germany',
    'JA': 'Japan',
    'IN': 'India',
    'CA': 'Canada',
    'AU': 'Australia',
    'BR': 'Brazil'
};
